### ISSUE TITLE
Cannot compile with 18.06.6

### ISSUE THREAD

**Issue by ilario** [aparcar/meta-imagebuilder#25]
Looks like one PGP key is missing?

```
download checksums and signature
verifying sha256sums signature
gpg: Signature made Thu 09 Jan 2020 01:27:43 PM CET
gpg:                using RSA key AD0507363D2BCE9C9E36CEC4FBCB78F015807931
gpg: Can't check signature: No public key
```

**Comment by aparcar** [comment]
Can you please try again? I though merging https://github.com/aparcar/openwrt-metabuilder/pull/24 would be enough...

**Comment by ilario** [comment]
I had to clone again in a new directory (no idea of which temporary file was the problem), then I had to install signify (which I didn't have) and now it works!! Magic!
